### ISSUE TITLE
Bug: Crossposting about the out of date `firacodenf` package from the NF repo

### ISSUE THREAD

**Issue by brian6932** [FredHappyface/Choco.Packages#3]
I prob should've reported it here first, but whatevs https://github.com/ryanoasis/nerd-fonts/issues/650
![image_240](https://user-images.githubusercontent.com/18603393/128866094-54fa1229-7777-4347-87a5-ef9d400907df.png)

**Comment by FredHappyface** [comment]
Fill in the template - not there to be ignored. Thanks
