### ISSUE TITLE
Feature: Fira Code Nerd Font Update to V6.2

### ISSUE THREAD

**Issue by michaelmyc** [FredHappyface/Choco.Packages#4]
## Feature

- [x] I have read the comment above and have completed each step
- [x] I have filled in each heading below

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

Upgrade Fira Code Nerd Font to [V6.2](https://github.com/tonsky/FiraCode/releases/tag/6.2).

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by FredHappyface** [comment]
Hi thanks for the issue 

I've updated the package https://community.chocolatey.org/packages/firacodenf/6.002 - just needs reviewing. Depending on how busy the chocolatey community/ maintainers are and if there is any feedback on this determines the timescale for the update 

Going forward I'm not sure how 'on the ball' I'm going to be with updates so if anyone want's to take over then let me know. I'll open another issue with more details

**Comment by FredHappyface** [comment]
Now publicly available
